#!/bin/bash
EXE_NAME=ar
function _agcc-msg { echo "[ar-dual-os]" "$@" >&2; }
function _agcc-dbg { [[ $AGCC_DBG ]] && _agcc-msg "$@"; }

###############################################################################
#Search the exe behind me in $PATH. Faster than using `which -a $EXE_NAME`.

IFS=: pathList=($PATH); unset IFS  #split $PATH by :, save to array

EXE_PATH=""; foundMyself=""
for d in "${pathList[@]}"; do
    if [[ -x $d/$EXE_NAME ]]; then
        if [[ $d/$EXE_NAME -ef "$0" ]]; then #is it actually myself? (symbol link also works)
            foundMyself=YES
        elif [[ $foundMyself ]]; then
            EXE_PATH=$d/$EXE_NAME
            break
        fi
    fi
done

if [[ ! $EXE_PATH ]]; then
    _agcc-msg "$EXE_NAME not found."
    exit 1
fi

###############################################################################

if [[ ! $AR_target ]]; then
    _agcc-msg "AR_target not defined."
    exit 1
fi

#AR_target maybe contains quot itself, so remove it first
AR_target="${AR_target//\"}"
#replace last "ar" with "objdump"
objdump=${AR_target/%ar/objdump}

###############################################################################

OBJ_FILE=""
for f in "$@"; do
    #find a non-zero *.o file
    if [[ ${f/*.} == o && -s $f ]]; then
        OBJ_FILE=$f
        break
    fi
done

if [[ $OBJ_FILE ]]; then
    #check .o file archive header by target objdump, if OK, then run target ar
    _agcc-dbg "check \"$OBJ_FILE\" by run \"$objdump\" -a on it"
    if "$objdump" -a "$OBJ_FILE" >/dev/null 2>/dev/null; then
        _agcc-msg "call \"$AR_target\""
        exec "$AR_target" "$@"
        exit
    fi
else
    _agcc-msg "no any non-empty *.o file provided for type check."
fi

#otherwise call host ar
_agcc-msg "call \"$EXE_PATH\""
exec "$EXE_PATH" "$@"
