#!/bin/bash
EXE_NAME=${0##*/}
function _agcc-msg { echo "[$EXE_NAME-lpthread]" "$@" >&2; }
function _agcc-dbg { [[ $AGCC_DBG ]] && _agcc-msg "$@"; }

###############################################################################
#Search the exe behind me in $PATH. Faster than using `which -a $EXE_NAME`.

case $EXE_NAME in
cc) ALT_EXE_NAME="gcc";;
gcc) ALT_EXE_NAME="cc";;
c++) ALT_EXE_NAME="g++";;
g++) ALT_EXE_NAME="c++";;
*) unset ALT_EXE_NAME;;
esac

IFS=: pathList=($PATH); unset IFS  #split $PATH by :, save to array

for name in $EXE_NAME $ALT_EXE_NAME; do
    EXE_PATH=""; foundMyself=""
    for d in "${pathList[@]}"; do
        if [[ -x $d/$name ]]; then
            if [[ $d/$name -ef "$0" ]]; then #is it actually myself? (symbol link also works)
                foundMyself=YES
            elif [[ $foundMyself ]]; then
                EXE_PATH=$d/$name
                break
            fi
        fi
    done
    [[ $EXE_PATH ]] && break;
done

if [[ ! $EXE_PATH ]]; then
    _agcc-msg "$EXE_NAME${ALT_EXE_NAME+ or }$ALT_EXE_NAME not found."
    exit 1
fi

###############################################################################
#if already have -lpthread option then run command without change.

has_lLIB=""
for arg in "$@"; do
    if [[ $arg == -lpthread ]]; then
        _agcc-dbg "call \"$EXE_PATH\" (already specified -lpthread option)"
        exec "$EXE_PATH" "$@"
        exit
    elif [[ $arg == -l* ]]; then
        has_lLIB=1
    fi
done

#if not sure how to insert -lpthread option then run command without change.
if [[ ! $has_lLIB ]]; then
    _agcc-dbg "call \"$EXE_PATH\" (no any -lLIB option)"
    exec "$EXE_PATH" "$@"
    exit
fi

###############################################################################
#otherwise run command with -lpthread

_agcc-msg "call \"$EXE_PATH\" with -lpthread"
exec "$EXE_PATH" "$@" -lpthread
